// Package keystore handles persistence of the project key: a raw key file used
// by the encoder and an obfuscated C header compiled into the decoder extension.
package keystore

import (
	"crypto/rand"
	"fmt"
	"os"
	"strings"

	"athena/internal/format"
)

// Save writes a raw 32-byte key file (mode 0600).
func Save(path string, key []byte) error {
	if len(key) != format.KeyLen {
		return fmt.Errorf("athena: key must be %d bytes", format.KeyLen)
	}
	return os.WriteFile(path, key, 0o600)
}

// Load reads a raw 32-byte key file.
func Load(path string) ([]byte, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(b) != format.KeyLen {
		return nil, fmt.Errorf("athena: key file %s is %d bytes, expected %d", path, len(b), format.KeyLen)
	}
	return b, nil
}

// WriteCHeader emits a C header that stores the key XOR-split across two arrays
// so the raw bytes never appear contiguously in the compiled .so. The extension
// reconstructs the key at MINIT via athena_key_load().
func WriteCHeader(path string, key []byte) error {
	if len(key) != format.KeyLen {
		return fmt.Errorf("athena: key must be %d bytes", format.KeyLen)
	}
	pad := make([]byte, format.KeyLen)
	if _, err := rand.Read(pad); err != nil {
		return err
	}
	enc := make([]byte, format.KeyLen)
	for i := range key {
		enc[i] = key[i] ^ pad[i]
	}

	var b strings.Builder
	b.WriteString("/* Generated by `athena keygen`. Do not edit. Do not commit. */\n")
	b.WriteString("#ifndef ATHENA_KEY_H\n#define ATHENA_KEY_H\n\n")
	b.WriteString("#include <stdint.h>\n\n")
	fmt.Fprintf(&b, "#define ATHENA_KEY_LEN %d\n", format.KeyLen)
	fmt.Fprintf(&b, "#define ATHENA_KEY_ID  0x%08xU\n\n", format.KeyID(key))
	writeArray(&b, "athena_key_a", enc)
	writeArray(&b, "athena_key_b", pad)
	b.WriteString("\n/* Reconstruct the key into out (must hold ATHENA_KEY_LEN bytes). */\n")
	b.WriteString("static inline void athena_key_load(unsigned char *out) {\n")
	b.WriteString("    for (int i = 0; i < ATHENA_KEY_LEN; i++)\n")
	b.WriteString("        out[i] = (unsigned char)(athena_key_a[i] ^ athena_key_b[i]);\n")
	b.WriteString("}\n\n#endif /* ATHENA_KEY_H */\n")

	return os.WriteFile(path, []byte(b.String()), 0o600)
}

func writeArray(b *strings.Builder, name string, data []byte) {
	fmt.Fprintf(b, "static const unsigned char %s[ATHENA_KEY_LEN] = {\n    ", name)
	for i, v := range data {
		fmt.Fprintf(b, "0x%02x,", v)
		if (i+1)%12 == 0 {
			b.WriteString("\n    ")
		} else if i != len(data)-1 {
			b.WriteString(" ")
		}
	}
	b.WriteString("\n};\n")
}
