/* Athena decoder extension.
 *
 * Overrides zend_compile_file: when a file contains an Athena container, its
 * payload is decrypted in memory and handed to the real compiler; otherwise
 * compilation proceeds untouched. OPcache, installed outermost, caches the
 * resulting op_array, so decryption happens only on a cache miss.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "php_ini.h"
#include "ext/standard/info.h"
#include "zend_compile.h"
#include "zend_stream.h"

#include "php_athena.h"
#include "container.h"
#include "athena_key.h" /* generated by `athena keygen -header` */

#include <sodium.h>
#include <string.h>

static zend_op_array *(*athena_orig_compile_file)(zend_file_handle *, int);
static unsigned char athena_key[ATHENA_KEYLEN];

static zend_op_array *athena_compile_file(zend_file_handle *file_handle, int type)
{
    char *buf = NULL;
    size_t len = 0;

    /* Load the file into memory (the compiler would do this anyway; once buf
     * is set on the handle, the real compiler reuses it instead of re-reading). */
    if (zend_stream_fixup(file_handle, &buf, &len) == FAILURE) {
        return athena_orig_compile_file(file_handle, type);
    }

    long off = athena_find_magic(buf, len);
    if (off < 0) {
        /* Not an Athena file — compile as normal. */
        return athena_orig_compile_file(file_handle, type);
    }

    unsigned char *src = NULL;
    size_t srclen = 0;
    int rc = athena_container_decrypt((const unsigned char *)buf + off,
                                      len - (size_t)off, athena_key,
                                      ATHENA_KEY_ID, &src, &srclen);
    if (rc != ATHENA_OK) {
        const char *fn = file_handle->filename ? ZSTR_VAL(file_handle->filename) : "?";
        zend_error(E_ERROR, "Athena: cannot decode %s: %s", fn, athena_strerror(rc));
        return NULL;
    }

    /* Replace the file buffer with the decrypted source. The compiler's lexer
     * reads ZEND_MMAP_AHEAD bytes past the end, which must be zeroed. */
    if (file_handle->buf) {
        efree(file_handle->buf);
    }
    char *nb = emalloc(srclen + ZEND_MMAP_AHEAD + 1);
    memcpy(nb, src, srclen);
    memset(nb + srclen, 0, ZEND_MMAP_AHEAD + 1);
    sodium_memzero(src, srclen);
    free(src);

    file_handle->buf = nb;
    file_handle->len = srclen;

    return athena_orig_compile_file(file_handle, type);
}

PHP_MINIT_FUNCTION(athena)
{
    if (sodium_init() < 0) {
        zend_error(E_WARNING, "Athena: libsodium initialization failed");
        return FAILURE;
    }
    athena_key_load(athena_key);

    athena_orig_compile_file = zend_compile_file;
    zend_compile_file = athena_compile_file;
    return SUCCESS;
}

PHP_MSHUTDOWN_FUNCTION(athena)
{
    if (zend_compile_file == athena_compile_file) {
        zend_compile_file = athena_orig_compile_file;
    }
    sodium_memzero(athena_key, sizeof(athena_key));
    return SUCCESS;
}

PHP_MINFO_FUNCTION(athena)
{
    php_info_print_table_start();
    php_info_print_table_row(2, "Athena decoder", "enabled");
    php_info_print_table_row(2, "Version", PHP_ATHENA_VERSION);
    php_info_print_table_row(2, "Container format", "v1 (XChaCha20-Poly1305)");
    php_info_print_table_end();
}

zend_module_entry athena_module_entry = {
    STANDARD_MODULE_HEADER,
    "athena",
    NULL,                     /* functions */
    PHP_MINIT(athena),
    PHP_MSHUTDOWN(athena),
    NULL,                     /* RINIT */
    NULL,                     /* RSHUTDOWN */
    PHP_MINFO(athena),
    PHP_ATHENA_VERSION,
    STANDARD_MODULE_PROPERTIES
};

#ifdef COMPILE_DL_ATHENA
#ifdef ZTS
ZEND_TSRMLS_CACHE_DEFINE()
#endif
ZEND_GET_MODULE(athena)
#endif
